version: "3"

services:
  web:
    build: .
    volumes:
      - ./media:/media
      - .:/app
    depends_on:
      - db
    environment:
      # Django settings overrides:
      - ALLOWED_HOSTS=*
      - DEBUG=True
      - DATABASE_URL=postgres://provider_service:provider_service@db:5432/provider_service_database
    command: >
      bash -c "urlwait &&
               ./manage.py migrate &&
               ./manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"

  db:
    image: mdillon/postgis
    environment:
      - POSTGRES_USER=${DATABASE_USER:-provider_service}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD:-provider_service}
      - POSTGRES_DB=provider_service_database
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
    db:
