# Generated by Django 2.2.3 on 2019-07-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
